# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.extras.delete]
  enable = true
[markup.goldmark.extensions.extras.insert]
  enable = true
[markup.goldmark.extensions.extras.mark]
  enable = true
[markup.goldmark.extensions.extras.subscript]
  enable = true
[markup.goldmark.extensions.extras.superscript]
  enable = true

# LaTeX math support
# https://gohugo.io/content-management/mathematics/
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4